version: "3.9"

networks:
  caddy_net:
    external: true

services:
  sircomform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sircomform
    restart: unless-stopped
    environment:
      FLASK_ENV: "production"
    networks:
      - caddy_net
    volumes:
      - /opt/sircom/drive-creds/credentials.json:/app/credentials.json:ro
      - /opt/sircom/drive-creds/token.json:/app/token.json
