version: "3.9"

networks:
  caddy_net:
    external: true

services:
  sircomform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sircomform
    restart: unless-stopped
    user: "0:0"     # <--- AGREGA ESTO (corre como root)
    environment:
      - FLASK_ENV=production
      # (opcional) rutas explícitas si quieres:
      # - GOOGLE_CREDENTIALS_FILE=/app/credentials.json
      # - GOOGLE_TOKEN_FILE=/app/token.json
    networks:
      - caddy_net
    volumes:
      - /opt/sircom/drive-creds/credentials.json:/app/credentials.json:ro
      - /opt/sircom/drive-creds/token.json:/app/token.json
